version: '3'

services:
  nest-proxy-service:
    container_name: nest-proxy-service
    image: admiraludon/nest-proxy-service:${APP_VERSION}
    ports:
      - 3000:3000
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./data/.env
        target: /app/.env
    platform: "linux/amd64"
    # env_file:
    #   - ./data/.env